version: "2.1"

networks:
  peering_v4:
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
  peering_v6:
    enable_ipv6: true
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_forwarding: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: fd83:7684:f21d:1337::/64
          ip_range: fd83:7684:f21d:1337:c1::/80

services:

  ipv6nat:
    container_name: ipv6nat
    restart: always
    image: robbertkl/ipv6nat
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
      
  routeserver:
    build: build_ixp/bird.rs.docker/.
    container_name: RouteServer
    restart: unless-stopped
    networks:
      peering_v4:
        ipv4_address: 10.10.1.2
      peering_v6:
        ipv6_address: fd83:7684:f21d:1337::2
    ports:
      - 179:179
    environment:
      PUID: 1001
      PGID: 1001
    volumes:
      - /opt/oceanixp/data/routeserver/bird.conf:/etc/bird/bird.conf
      - /opt/oceanixp/data/routeserver/bird6.conf:/etc/bird/bird6.conf
      - /opt/oceanixp/logs/routeserver/bird.log:/var/log/bird.log
      - /opt/oceanixp/logs/routeserver/bird6.log:/var/log/bird6.log
      
  arouteserver:
    build: build_ixp/rs.gen.docker/.
    container_name: arouteserver
    restart: unless-stopped
    network_mode: host
    environment:
      SETUP_AND_CONFIGURE_AROUTESERVER: 0
      PUID: 1001
      PGID: 1001
    volumes:
      - /opt/oceanixp/data/routeserver/bird.conf:/etc/bird/bird.conf
      - /opt/oceanixp/data/routeserver/bird6.conf:/etc/bird/bird6.conf
      - /opt/oceanixp/data/arouteserver/clients.yml:/root/clients.yml
      - /opt/oceanixp/data/arouteserver/general.yml:/etc/arouteserver/general.yml
      - /opt/oceanixp/logs/arouteserver/bird.log:/var/log/bird.log

  watchtower: 
   image: containrrr/watchtower
   container_name: Watchtower
   restart: unless-stopped
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   command: --interval 500

  portainer: 
    image: portainer/portainer-ce
    container_name: Portainer
    restart: unless-stopped
    environment:
      PUID: 1001
      PGID: 1001
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/oceanixp/data/portainer/:/data
